#!/bin/bash
ANDROID_HOME=~/.buildozer/android/platform/android-sdk-21
ADB=$ANDROID_HOME/platform-tools/adb
CLASSPATH=$ANDROID_HOME/platforms/android-14/android.jar
set -x

cd /media/JTC/java
javac -classpath $CLASSPATH  org/jtc/planilla/*.java
jar -cf PlanillaHelper.jar org/jtc/planilla/*.class

cd ~/kivy/JTC/; cp /media/JTC/*.{py,kv,csv,json} .
cp /media/JTC/service/*.py service
cp /media/JTC/java/*.jar java

python -OO -m compileall -f -l . service

if [ -n "$1" ]
then
	echo argumento $1
#	~/jscp.py $1
	scp -r *.{pyo,kv,csv,json} service root@$1:/data/data/org.jtc.planilla/files/
else
	echo Falta dirección del ssh
fi

$ADB shell am force-stop org.jtc.planilla
$ADB shell am start -n org.jtc.planilla/org.renpy.android.PythonActivity -a org.renpy.android.PythonActivity
