#!/bin/bash
#ANDROID_HOME=~/.buildozer/android/platform/android-sdk-21
#ADB=$ANDROID_HOME/platform-tools/adb
#CLASSPATH=$ANDROID_HOME/platforms/android-14/android.jar
set -x

git describe --tags > version.txt

# javac -classpath $CLASSPATH  org/jtc/planilla/*.java
# jar -cf PlanillaHelper.jar org/jtc/planilla/*.class

python -OO -m compileall -f -l . service

if [ -n "$1" ]
then
	echo argumento $1
	FILES=`echo *.{pyo,kv,csv,json} version.txt service`
	expect -c "
        spawn /usr/bin/scp -r $FILES root@$1:/data/data/org.jtc.planilla/files/
        expect {
          "*password:*" { send "cunter38"\r\n; interact }
          eof { exit }
        }
        exit
        "
else
	echo Falta dirección del ssh
fi

adb shell am force-stop org.jtc.planilla
adb shell am start -n org.jtc.planilla/org.renpy.android.PythonActivity -a org.renpy.android.PythonActivity
